### ISSUE TITLE
Bug Custodian API - GET /credentials/listCredentialIds returns 404

### ISSUE THREAD

**Issue by 0xCaso** [walt-id/waltid-ssikit#148] opened 2022-07-28 09:50 UTC
The GET method returns 404 every time it's called.

To reproduce the bug, you can:

1. store a credential calling `/credential/{alias}`
2. call `/credentials` and see the list, with the new credential just added
3. call `/credentials/listCredentialIds` and returns 404

It should return the ids of all credentials I know, so at least the last one I've stored.

![Screenshot from 2022-07-28 11-43-33](https://user-images.githubusercontent.com/22419450/181475389-f97401f2-61f8-425a-9333-c1d3bc07ec32.png)

**Comment by 0xCaos** [comment] 2022-08-04 14:24
I've just retried on swagger and still the bug figures out (I've re-cloned the repo and re-build), in the same way described above.

I don't think the problem relies in `listCredentialIds` function in [FileSystemVcStoreService](https://github.com/walt-id/waltid-ssikit/blob/master/src/main/kotlin/id/walt/services/vcstore/FileSystemVcStoreService.kt) class, as `listCredential` calls `listCredentialIds` but it works. Maybe it's something at higher level? 

Seems like the swagger function `listCredentialIds` calls `getCredential` of [CustodianController](https://github.com/walt-id/waltid-ssikit/blob/fb96ecb2e02409791fa7aae4126b0094bdcd7c1e/src/main/kotlin/id/walt/rest/custodian/CustodianController.kt) class, as it returns "error 404" (and the only function which returns it is `getCredential`).

**Comment by philpotisk** [comment] 2022-08-05 06:50
Hey @0xCaos you are definitely right about this issue. I have actually fixed one problem with the CLI tool, but there seems to be another problem at the rest-layer remaining. I guess it has to do with the encoding of credentials. Thanks for raising this issue! We will fix it soon.

**Closed** 2022-08-08 00:00 UTC
Labels: bug

**Comment by waltkb** [comment] 2022-08-08 00:03
Hi @0xCaos, your issue was fixed and the bug no longer reproduces beginning with e3d26941.
